# Generated by Django 6.0.7 on 2026-07-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tarmoq nomi (Telegram, YouTube...)')),
                ('link', models.URLField(verbose_name='Havola (Link)')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name="O'quvchi ismi")),
                ('class_name', models.CharField(max_length=20, verbose_name='Sinfi')),
                ('certificate', models.ImageField(upload_to='certificates/', verbose_name='Sertifikat rasmi')),
                ('description', models.CharField(max_length=255, verbose_name='Nima uchun berilgan')),
            ],
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.AlterField(
            model_name='graduate',
            name='achievement',
            field=models.CharField(max_length=255, verbose_name="Yutug'i (OTM yoki ish)"),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='F.I.Sh'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='image',
            field=models.ImageField(upload_to='graduates/', verbose_name='Rasmi'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='year',
            field=models.IntegerField(verbose_name='Bitirgan yili'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True, verbose_name="Ma'lumot"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='F.I.Sh'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to='teachers/', verbose_name='Rasmi'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Fani'),
        ),
    ]
