# Generated by Django 6.0.7 on 2026-07-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sociallink_studentportfolio_delete_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Matni')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
        ),
        migrations.AlterField(
            model_name='graduate',
            name='achievement',
            field=models.CharField(max_length=255, verbose_name="Yutug'i"),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentportfolio',
            name='certificate',
            field=models.ImageField(upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='studentportfolio',
            name='class_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentportfolio',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentportfolio',
            name='student_name',
            field=models.CharField(max_length=100),
        ),
    ]
