# Generated by Django 6.0.7 on 2026-07-14 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_alter_graduate_achievement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Yutuq nomi')),
                ('image', models.ImageField(upload_to='certificates/', verbose_name='Sertifikat rasmi')),
                ('description', models.TextField(verbose_name="Batafsil ma'lumot")),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Sinf nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='F.I.Sh')),
                ('photo', models.ImageField(upload_to='students/', verbose_name='Rasmi')),
                ('rank', models.CharField(max_length=100, verbose_name="Maktabdagi o'rni/vazifasi")),
                ('bio', models.TextField(verbose_name="O'quvchi haqida qisqacha")),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.grade')),
            ],
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
        migrations.DeleteModel(
            name='StudentPortfolio',
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='main.student'),
        ),
    ]
