# Generated by Django 6.0.7 on 2026-07-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_achievement_grade_student_delete_sociallink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(verbose_name='Batafsil'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='achievement',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='image',
            field=models.ImageField(upload_to='graduates/'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.TextField(verbose_name="O'quvchi haqida"),
        ),
        migrations.AlterField(
            model_name='student',
            name='rank',
            field=models.CharField(max_length=100, verbose_name="Maktabdagi o'rni"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to='teachers/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
