# Generated by Django 6.0.7 on 2026-07-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_achievement_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='FontAwesome klassi (masalan: fas fa-user-graduate)', max_length=100)),
                ('value', models.CharField(help_text='Qiymati (masalan: 450+)', max_length=20)),
                ('label_uz', models.CharField(max_length=100, verbose_name='Nomi (UZ)')),
                ('label_en', models.CharField(max_length=100, verbose_name='Nomi (EN)')),
                ('label_ru', models.CharField(max_length=100, verbose_name='Nomi (RU)')),
            ],
        ),
    ]
