# Generated by Django 6.0.7 on 2026-07-22 07:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_schoolstat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='main_image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='rank',
        ),
        migrations.AddField(
            model_name='grade',
            name='academic_year',
            field=models.CharField(default='2025-2026', max_length=20),
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_classes', to='main.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements_list', to='main.student'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolstat',
            name='icon_class',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolstat',
            name='label_en',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolstat',
            name='label_ru',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolstat',
            name='label_uz',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolstat',
            name='value',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='students/'),
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/gallery/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.news')),
            ],
        ),
    ]
