# Generated by Django 6.0.7 on 2026-07-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_image_news_main_image_remove_student_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
