# Generated by Django 6.0.7 on 2026-07-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_student_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='degree',
            field=models.CharField(choices=[('oliy', "Oliy ma'lumotli mutaxassis"), ('1-daraja', '1-darajali mutaxassis'), ('2-daraja', '2-darajali mutaxassis')], default='mutaxassis', max_length=20, verbose_name='Darajasi'),
        ),
    ]
