# Generated by Django 6.0.7 on 2026-07-23 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_teacher_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolstat',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='achievements',
        ),
        migrations.AddField(
            model_name='schoolstat',
            name='icon_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='stats/icons/', verbose_name='Ikonka (Flaticon)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolstat',
            name='label_en',
            field=models.CharField(max_length=100, verbose_name='Nomi (EN)'),
        ),
        migrations.AlterField(
            model_name='schoolstat',
            name='label_ru',
            field=models.CharField(max_length=100, verbose_name='Nomi (RU)'),
        ),
        migrations.AlterField(
            model_name='schoolstat',
            name='label_uz',
            field=models.CharField(max_length=100, verbose_name='Nomi (UZ)'),
        ),
        migrations.AlterField(
            model_name='schoolstat',
            name='value',
            field=models.CharField(max_length=20, verbose_name='Qiymat (masalan: 450+)'),
        ),
    ]
