# Generated by Django 6.0.7 on 2026-07-24 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_schoolstat_icon_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='achievements',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], default='M', max_length=1, verbose_name='Jinsi'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], default='M', max_length=1, verbose_name='Jinsi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TeacherAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sertifikat nomi')),
                ('image', models.ImageField(upload_to='teachers/certificates/')),
                ('description', models.TextField(blank=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements_list', to='main.teacher')),
            ],
        ),
    ]
