# Generated by Django 6.0.7 on 2026-07-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_teacher_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Lavozimi (masalan: Maktab direktori, Xalq o'qituvchisi)"),
        ),
    ]
