# Generated by Django 6.0.7 on 2026-07-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_teacher_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Layklar'),
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar"),
        ),
    ]
