# Generated by Django 6.0.7 on 2026-07-31 09:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_news_likes_news_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='album',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rasm tavsifi (ixtiyoriy)'),
        ),
        migrations.DeleteModel(
            name='GalleryAlbum',
        ),
    ]
