# Generated by Django 6.0.7 on 2026-08-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_galleryimage_album_galleryimage_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduate',
            name='year',
        ),
        migrations.AddField(
            model_name='achievement',
            name='is_national',
            field=models.BooleanField(default=False, verbose_name='Milliy sertifikat'),
        ),
        migrations.AddField(
            model_name='graduate',
            name='academic_year',
            field=models.CharField(default='2025-2026', max_length=20, verbose_name="O'quv yili"),
        ),
        migrations.AddField(
            model_name='graduate',
            name='is_early_graduate',
            field=models.BooleanField(default=False, verbose_name='Muddatidan avval bitirgan'),
        ),
        migrations.AddField(
            model_name='graduate',
            name='university',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kirgan universiteti'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='achievement',
            field=models.CharField(max_length=255, verbose_name='Hozirda (faoliyati)'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='image',
            field=models.ImageField(upload_to='graduates/', verbose_name='Rasm'),
        ),
    ]
