# Generated by Django 6.0.7 on 2026-08-06 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_graduate_year_achievement_is_national_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduateAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255, verbose_name='Universitet nomi')),
                ('is_studying', models.BooleanField(default=False, verbose_name="Aynan shu yerda o'qiydi")),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='main.graduate')),
            ],
        ),
        migrations.RunPython(
            # Eski 'university' maydonidagi ma'lumotni GraduateAdmission'ga ko'chirish
            lambda apps, schema_editor: _migrate_university(apps, schema_editor),
            # Qaytarish: o'chirish
            lambda apps, schema_editor: _revert(apps, schema_editor),
        ),
        migrations.RemoveField(
            model_name='graduate',
            name='university',
        ),
    ]


def _migrate_university(apps, schema_editor):
    Graduate = apps.get_model('main', 'Graduate')
    GraduateAdmission = apps.get_model('main', 'GraduateAdmission')
    for g in Graduate.objects.all():
        uni = getattr(g, 'university', '') or ''
        uni = uni.strip()
        if uni:
            GraduateAdmission.objects.create(graduate=g, university=uni, is_studying=True)


def _revert(apps, schema_editor):
    Graduate = apps.get_model('main', 'Graduate')
    GraduateAdmission = apps.get_model('main', 'GraduateAdmission')
    for g in Graduate.objects.all():
        adm = GraduateAdmission.objects.filter(graduate=g, is_studying=True).first() or \
              GraduateAdmission.objects.filter(graduate=g).first()
        if adm:
            g.university = adm.university
            g.save()
